# =======================================
# Name: Rowan Tilroe
# ID: 1629172
# CMPUT 274, Fall 2019
#
# Weekly exercise #2: Unfair Dice
# =======================================

from random import random
from random import seed


def biased_rolls(prob_list, s, n):
    """ Simulate n rolls of a biased m-sided die and return
    a list containing the results.

    Arguments:
        prob_list: a list of the probabilities of rolling the
                   number on each side of the m-sided die. The list
                   will always have the length m (m >= 2), where m is
                   the number of sides numbered 1 to m. Therefore,
                   for example, the probability stored at index 0 in
                   the list is the probability of rolling a 1 on
                   the m-sided die.
        s: the seed to use when initializing the PRNG
        n: the number of rolls to return

    Return:
        rolls: a list (of length n) containing each of the n rolls of the
               biased die, in the order they were generated.
    """
    # ============================================

    seed(s)

    # generate rolls
    rolls = []

    for i in range(n):

        random_float = random()
        counter = 0
        current_listLocation = prob_list[counter]

        while random_float > current_listLocation:
            last_listLocation = current_listLocation
            counter += 1
            current_listLocation = prob_list[counter] + last_listLocation

        roll = counter + 1
        rolls.append(roll)

    # return the resulting rolls
    return rolls


def draw_histogram(m, rolls, width):
    """ Draws a frequency histogram of the rolls of an m-sided die
    mapped to a fixed width.

    Arguments:
        m (int): the number of sides on the die
        rolls (list): the list of rolls generated by the biased die
        width (int): the fixed width of the histogram, in characters
                     (this is the length of the longest bar in the
                     histogram, to maximize space in the chart)

    Returns:
        None (but prints the histogram to standard output)
    """
    # ============================================

    # Count rolls per number and establish asterisksPerRoll
    rollcountlist = []

    for i in range(m):
        roll = i+1
        rollcount = rolls.count(roll)
        rollcountlist.append(rollcount)

    asterisksPerRoll = width/(max(rollcountlist))

    # Output
    print("Frequency Histogram: {0}-sided Die".format(m))

    for i in range(m):
        print("{0}:".format(i+1), end="")
        rollsForThisSide = rollcountlist[i]
        asterisks = round(rollsForThisSide * asterisksPerRoll)
        dashes = width - asterisks

        for i in range(asterisks):
            print("*", end="")
        for i in range(dashes):
            print("-", end="")
        print("")


# ============================================

# Main program

if __name__ == "__main__":
    rolls = biased_rolls([1/4, 1/6, 1/12, 1/12, 1/4, 1/6], 42, 200)
    draw_histogram(6, rolls, 10)